stages:
  - Test

# Check if logo.png in the root of the repo corresponds to the content of assets/src/logo.svg.
logo:
  stage: Test
  image: madhead/imagemagick
  script:
    - convert -background none -density 300 -resize 128x128 assets/src/logo.svg logo.check.png
    - magick compare -verbose -metric ae logo.png logo.check.png diff.png
  artifacts:
    name: $CI_COMMIT_SHA-$CI_JOB_NAME
    paths:
      - diff.png
    expire_in: 1 day
    when: on_failure

gradle-version:
  stage: Test
  image: openjdk:13
  dependencies: []
  script:
    - gradle_version=$(./gradlew --version | sed -rn 's/^Gradle (.+)$/\1/p')
    - latest_gradle_version=$(curl https://services.gradle.org/versions/current | python2 -c 'import json,sys;print json.load(sys.stdin)["version"]')
    - echo $gradle_version
    - echo $latest_gradle_version
    - '[[ $gradle_version == $latest_gradle_version ]]'
